// @flow
// flow-typed signature: 27196c2b998a34ab31b6e46e5616b89f
// flow-typed version: <<STUB>>/fancy-log_v1.3.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fancy-log'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fancy-log' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'fancy-log/index' {
  declare module.exports: $Exports<'fancy-log'>;
}
declare module 'fancy-log/index.js' {
  declare module.exports: $Exports<'fancy-log'>;
}
