// @flow
// flow-typed signature: 702ec406b5066f26495a1ad7c367c7aa
// flow-typed version: <<STUB>>/lodash.defaultsdeep_v4.6.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.defaultsdeep'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.defaultsdeep' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.defaultsdeep/index' {
  declare module.exports: $Exports<'lodash.defaultsdeep'>;
}
declare module 'lodash.defaultsdeep/index.js' {
  declare module.exports: $Exports<'lodash.defaultsdeep'>;
}
