// flow-typed signature: 9eabde0e70d9f7956c0b7b51e1fba6bc
// flow-typed version: <<STUB>>/node-yaml_v3.1.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-yaml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-yaml' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-yaml/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-yaml/main.js' {
  declare module.exports: $Exports<'node-yaml/main'>;
}
