workflows:
  version: 2
  node-multi-build:
    jobs:
    - test-node-v10
    - test-node-v8.10
    - release:
        requires:
        - test-node-v10
        - test-node-v8.10
        filters:
          branches:
            only: master
version: 2
jobs:
  test-node-v10:
    docker:
    - image: 'circleci/node:10'
    steps:
    - checkout
    - run: npm i
    - run: npm t
  test-node-v8.10:
    docker:
    - image: 'circleci/node:8.10'
    steps:
    - checkout
    - run: npm i
    - run: npm t
  release:
    docker:
    - image: 'circleci/node:10'
    steps:
    - checkout
    - run: npm i
    - run: npm run semantic-release
